# Generated by Django 3.1.2 on 2020-11-03 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_name',
            field=models.CharField(choices=[], max_length=120),
        ),
    ]
