# Generated by Django 3.1.2 on 2020-11-05 05:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('neighbourhood_name', models.CharField(choices=[('Langata', 'Langata'), ('Dagoretti', 'Dagoretti'), ('Embakasi', 'Embakasi'), ('CBD', 'CBD'), ('Kasarani', 'Kasarani'), ('Kibra', 'Kibra'), ('Westland', 'Westland'), ('Parkland', 'Parkland')], max_length=120)),
            ],
        ),
        migrations.RemoveField(
            model_name='neighbourhood',
            name='neighbourhood_name',
        ),
        migrations.AddField(
            model_name='neighbourhood',
            name='hood_name',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, related_name='hood_name', to='neighbour.name'),
            preserve_default=False,
        ),
    ]
