# Generated by Django 3.1.2 on 2020-11-04 07:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_remove_profile_neighbourhood'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='neighbourhood',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='neighbour.neighbourhood'),
            preserve_default=False,
        ),
    ]
