# Generated by Django 3.1.2 on 2020-11-02 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0002_auto_20201102_0753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='job_title',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='location',
        ),
    ]
