# Generated by Django 3.1.2 on 2020-11-02 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_auto_20201102_0757'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='neighbourhood',
        ),
    ]
