# Generated by Django 3.1.2 on 2020-11-05 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0003_post_neighbour_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='neighbour_name',
            new_name='neighbour',
        ),
    ]
