# Generated by Django 3.1.2 on 2020-11-04 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_auto_20201104_1047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='bio',
            field=models.TextField(default='me', max_length=120),
        ),
    ]
