# Generated by Django 3.1.2 on 2020-11-02 05:31

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0004_remove_profile_neighbourhood'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='Country',
            new_name='location',
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('title', models.CharField(max_length=120, null=True)),
                ('content', models.TextField(max_length=1000, null=True, verbose_name='project Description')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_profile', to='neighbour.profile')),
            ],
        ),
    ]
