# Generated by Django 3.1.2 on 2020-11-04 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0005_auto_20201103_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('1', 'Lost and Found'), ('2', 'Health Emergency'), ('3', 'Fire Breakouts'), ('4', 'Crimes and Safety'), ('5', 'Death'), ('6', 'Event'), ('7', 'Document'), ('8', 'Job')], default=1, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=1000, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='post',
            name='profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='your_profile', to='neighbour.profile'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=120),
        ),
    ]
