# Generated by Django 3.1.2 on 2020-11-04 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0006_auto_20201104_0825'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='description',
            field=models.TextField(default='This business is a neighbourhood thing.. like charity... so be prepared for unpaid job... make good use of yourself', max_length=1000, verbose_name='j_d'),
            preserve_default=False,
        ),
    ]
