# Generated by Django 3.1.2 on 2020-11-04 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('neighbour', '0007_auto_20201104_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='neighbourhood',
            name='neighbourhood_name',
            field=models.CharField(choices=[('Langata', 'Langata'), ('Dagoretti', 'Dagoretti'), ('Embakasi', 'Embakasi'), ('CBD', 'CBD'), ('Kasarani', 'Kasarani'), ('Kibra', 'Kibra'), ('Westland', 'Westland'), ('Parkland', 'Parkland')], max_length=120),
        ),
    ]
